// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pndtqzkoysrllwgxxxed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuZHRxemtveXNybGx3Z3h4eGVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTExMTYsImV4cCI6MjA3NzQ2NzExNn0.kuy_jCqEHQG4_mfDKWHxTi850kW9MHSiamRMrQrWU7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});